# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Upper-triangle index pairs
#' @param len Number of codes (side length of square matrix)
#' @param row -1 = both rows, 0 = row indices only, 1 = col indices only
#' @export
lq_tri_indices <- function(len, row = -1L) {
    .Call(`_libqe_lq_tri_indices`, len, row)
}

#' Pairwise products → upper-triangle vector
#' @param v Numeric vector of code values
#' @export
lq_vector_to_upper_tri <- function(v) {
    .Call(`_libqe_lq_vector_to_upper_tri`, v)
}

#' Fold a directed (n*n) vector into an undirected upper-triangle vector
#' @param v Numeric vector of length n*n
#' @export
lq_directed_to_upper_tri <- function(v) {
    .Call(`_libqe_lq_directed_to_upper_tri`, v)
}

#' Flatten an adjacency matrix to a connection vector
#' @param x Numeric matrix
#' @param full TRUE = full n*n (directed); FALSE = upper triangle (undirected)
#' @export
lq_adjacency_matrix_to_vector <- function(x, full = TRUE) {
    .Call(`_libqe_lq_adjacency_matrix_to_vector`, x, full)
}

#' Code-name pairs for upper-triangle positions ("A & B")
#' @param v Character vector of code names
#' @export
lq_svector_to_upper_tri <- function(v) {
    .Call(`_libqe_lq_svector_to_upper_tri`, v)
}

#' Row-wise L2 (sphere) normalization
#' @param m Numeric matrix
#' @export
lq_sphere_norm <- function(m) {
    .Call(`_libqe_lq_sphere_norm`, m)
}

#' Max-norm scaling (divide all rows by the largest row L2 norm)
#' @param m Numeric matrix
#' @export
lq_skip_sphere_norm <- function(m) {
    .Call(`_libqe_lq_skip_sphere_norm`, m)
}

#' Center data (subtract column means)
#' @param values Numeric matrix
#' @export
lq_center_data <- function(values) {
    .Call(`_libqe_lq_center_data`, values)
}

#' Confidence interval for the mean of a group of ENA unit points
#'
#' For each dimension computes a t-based CI:
#' \code{mean ± t(α/2, n-1) × (SD / sqrt(n))} where \code{α = 1 - conf_level}.
#'
#' @param points     Numeric matrix (units x dims) — one row per unit in the group
#' @param conf_level Confidence level (default 0.95)
#' @return Numeric matrix (n_dims x 3): columns are [mean, ci_lower, ci_upper].
#'   When \code{nrow(points) == 1} the CI bounds are \code{±Inf}.
#' @export
lq_group_ci <- function(points, conf_level = 0.95) {
    .Call(`_libqe_lq_group_ci`, points, conf_level)
}

#' Outlier interval based on IQR (Tukey fence) for a group of ENA unit points
#'
#' For each dimension: \code{lower = -iqr_factor * IQR}, \code{upper = +iqr_factor * IQR}.
#' Equivalent to rENA's:
#' \preformatted{
#'   oi <- c(IQR(pts[,1]), ...) * iqr_factor
#'   matrix(rep(oi, 2), ncol = n_dims, byrow = TRUE) * c(-1, 1)
#' }
#' IQR uses R's default \code{type = 7} quantile.
#'
#' @param points     Numeric matrix (units x dims) — one row per unit in the group
#' @param iqr_factor Multiplier applied to the IQR (default 1.5, the Tukey fence)
#' @return Numeric matrix (n_dims x 2): columns are [lower, upper].
#' @export
lq_outlier_ci <- function(points, iqr_factor = 1.5) {
    .Call(`_libqe_lq_outlier_ci`, points, iqr_factor)
}

#' Pearson correlation with CI between ENA points and centroids
#' @param points  Numeric matrix (units x dims)
#' @param centroids Numeric matrix (units x dims)
#' @param conf_level Confidence level (default 0.95)
#' @export
lq_ena_correlation <- function(points, centroids, conf_level = 0.95) {
    .Call(`_libqe_lq_ena_correlation`, points, centroids, conf_level)
}

#' Least-squares node positions for undirected ENA
#' @param adj_mats Numeric matrix of line weights (units x connections)
#' @param t        Numeric matrix of rotated points (units x dims)
#' @param num_dims Number of dimensions
#' @return List with nodes, centroids, weights, points
#' @export
lq_lws_lsq_positions <- function(adj_mats, t, num_dims) {
    .Call(`_libqe_lq_lws_lsq_positions`, adj_mats, t, num_dims)
}

#' Least-squares node positions for directed ENA
#' @param line_weights Numeric matrix (units x connections)
#' @param points       Numeric matrix of rotated points (units x dims)
#' @param num_dims     Number of dimensions
#' @return List with nodes, centroids, weights, points
#' @export
lq_directed_node_positions <- function(line_weights, points, num_dims) {
    .Call(`_libqe_lq_directed_node_positions`, line_weights, points, num_dims)
}

#' Directed node positions with paired ground+response rows combined
#' @param line_weights Numeric matrix (units x connections)
#' @param points       Numeric matrix of rotated points (units x dims)
#' @param num_dims     Number of dimensions
#' @return List with nodes, centroids, weights, points
#' @export
lq_directed_node_positions_ground_response <- function(line_weights, points, num_dims) {
    .Call(`_libqe_lq_directed_node_positions_ground_response`, line_weights, points, num_dims)
}

#' Core adjacency matrix for one ground+response pair
#' @param ground          Numeric row vector of ground (context) code values
#' @param response        Numeric row vector of response code values
#' @param response_weight Scalar weight applied to the response self-connection
#' @param ordered         TRUE = directed; FALSE = undirected
#' @export
lq_calculate_adjacency_matrix <- function(ground, response, response_weight = 1.0, ordered = TRUE) {
    .Call(`_libqe_lq_calculate_adjacency_matrix`, ground, response, response_weight, ordered)
}

#' Traditional stanza-window accumulation (rENA model)
#'
#' For each row k in a single conversation's code matrix, accumulates
#' co-occurrences over a back/forward window and returns the upper-triangle
#' connection vector.
#'
#' @param codes          Numeric matrix (rows = lines, cols = codes) for ONE conversation
#' @param window_back    Number of prior lines in window (default 1); use .Machine$integer.max for Inf
#' @param window_forward Number of subsequent lines (default 0)
#' @param binary         If TRUE, binarise non-zero connection counts
#' @return Numeric matrix (same n_rows, choose_two(n_codes) columns)
#' @export
lq_stanza_window <- function(codes, window_back = 1L, window_forward = 0L, binary = TRUE) {
    .Call(`_libqe_lq_stanza_window`, codes, window_back, window_forward, binary)
}

#' Compute a column-major linear index into a multi-dimensional array
#'
#' Equivalent to tma's calculate_1d_index(). Throws if lengths of `indices`
#' and `dims` differ.
#'
#' @param indices 0-based integer vector of per-dimension indices
#' @param dims    Integer vector of array dimensions
#' @return Scalar integer linear index
#' @export
lq_calculate_1d_index <- function(indices, dims) {
    .Call(`_libqe_lq_calculate_1d_index`, indices, dims)
}

#' Per-row upper-triangle co-occurrence matrix
#'
#' For each row in \code{codes}, computes the pairwise code products
#' (upper-triangle) and optionally binarizes. Output has
#' \code{choose(n_codes, 2)} columns.
#'
#' @param codes  Numeric matrix (rows = observations, cols = codes)
#' @param binary If TRUE, binarise non-zero co-occurrences (default TRUE)
#' @return Numeric matrix (n_rows x choose_two(n_codes))
#' @export
lq_rows_to_co_occurrences <- function(codes, binary = TRUE) {
    .Call(`_libqe_lq_rows_to_co_occurrences`, codes, binary)
}

#' Rolling backward window sum of a code matrix
#'
#' For each row k, sums the raw code values over rows
#' \code{[max(0, k - window_size + 1), k]}. Returns a matrix of the same
#' shape as \code{codes}. \code{window_size <= 0} is treated as 1
#' (current row only).
#'
#' @param codes       Numeric matrix (rows = observations, cols = codes)
#' @param window_size Number of rows to look back (default 1)
#' @return Numeric matrix (same dimensions as \code{codes})
#' @export
lq_rolling_window_sum <- function(codes, window_size = 1L) {
    .Call(`_libqe_lq_rolling_window_sum`, codes, window_size)
}

#' Ground/response accumulation for one unit (tma model)
#'
#' @param codes      Numeric matrix for the full context (n_rows x n_codes)
#' @param unit_rows  0-based integer vector of rows belonging to this unit
#' @param decay_fn   R function mapping a numeric distance vector to weights
#' @param ordered    TRUE = directed; FALSE = undirected (upper-tri)
#' @return Numeric vector of connection counts
#' @export
lq_accumulate_unit <- function(codes, unit_rows, decay_fn, ordered = FALSE) {
    .Call(`_libqe_lq_accumulate_unit`, codes, unit_rows, decay_fn, ordered)
}

#' Ground/response accumulation for one unit — returns unit vector and per-row matrix
#'
#' Equivalent to tma's accumulate_network() but without R-env-var setup.
#' The decay function receives a distance vector (response=0, older rows
#' have larger values) and returns a weight vector of the same length.
#'
#' @param codes      Numeric matrix (n_rows x n_codes)
#' @param unit_rows  0-based integer vector of rows belonging to this unit
#' @param decay_fn   R function(distances) -> weights
#' @param ordered    TRUE = directed (full p^2); FALSE = undirected (upper-tri)
#' @return List with `networks` (vector) and `row_networks` (matrix)
#' @export
lq_accumulate_unit_with_rows <- function(codes, unit_rows, decay_fn, ordered = FALSE) {
    .Call(`_libqe_lq_accumulate_unit_with_rows`, codes, unit_rows, decay_fn, ordered)
}

#' Tensor-based multi-modal accumulation for one unit (tma model)
#'
#' Pure-C++ port of tma's apply_tensor().  Accepts 0-based index vectors
#' for sender/receiver/mode dimensions and a pre-converted integer context
#' lookup matrix.
#'
#' @param tensor         Numeric vector (column-major flat tensor)
#' @param dims           Integer vector of tensor dimensions
#' @param dims_sender    0-based sender axis indices
#' @param dims_receiver  0-based receiver axis indices
#' @param dims_mode      0-based mode axis indices
#' @param context_lookup Integer matrix (n_context_rows x n_factors), 0-based
#' @param unit_rows      0-based response-row indices for this unit
#' @param codes          Numeric matrix (n_context_rows x n_codes)
#' @param times          Numeric vector of timestamps per context row
#' @param ordered        TRUE = directed; FALSE = undirected
#' @return List with `connection_counts` (vector) and `row_connection_counts` (matrix)
#' @export
lq_apply_tensor <- function(tensor, dims, dims_sender, dims_receiver, dims_mode, context_lookup, unit_rows, codes, times, ordered = TRUE) {
    .Call(`_libqe_lq_apply_tensor`, tensor, dims, dims_sender, dims_receiver, dims_mode, context_lookup, unit_rows, codes, times, ordered)
}

#' SVD rotation (matches prcomp(retx=F, scale=F, center=F, tol=0))
#'
#' Caller is responsible for centering upstream. Eigenvalues are stored as
#' \code{sdev^2} (variance) to match rENA's \code{ena.svd}.
#'
#' @param points Numeric matrix (n_units x n_dims)
#' @return List with \code{rotation} (n_dims x n_dims), \code{eigenvalues}
#'   (length n_dims, = sdev^2), and \code{column_names} ("SVD1", "SVD2", ...)
#' @export
lq_ena_svd <- function(points) {
    .Call(`_libqe_lq_ena_svd`, points)
}

#' Project a matrix onto the hyperplane orthogonal to a unit-norm axis
#'
#' Computes \code{data - (data \%*\% axis) \%*\% t(axis)}. The caller is
#' responsible for ensuring \code{axis} is unit-norm.
#'
#' @param data Numeric matrix (n_units x n_dims)
#' @param axis Numeric vector of length n_dims, unit-norm
#' @return Numeric matrix of the same shape as \code{data}
#' @export
lq_deflate <- function(data, axis) {
    .Call(`_libqe_lq_deflate`, data, axis)
}

#' Orthogonal SVD — orthonormalize named axes via QR, fill the rest from SVD
#'
#' Mirrors rENA's \code{orthogonal_svd()} in \code{ena.rotate.by.mean.R}:
#' the named axes in the output are the orthonormalized Q columns, not the
#' original \code{weights} columns. Use \code{lq_complete_rotation} to keep
#' the named axes verbatim.
#'
#' @param data         Numeric matrix (n_units x n_dims)
#' @param weights      Numeric matrix (n_dims x k); columns are the named axes
#' @param named_labels Character vector of length k
#' @return List with \code{rotation}, \code{eigenvalues}, \code{column_names}
#' @export
lq_orthogonal_svd <- function(data, weights, named_labels) {
    .Call(`_libqe_lq_orthogonal_svd`, data, weights, named_labels)
}

#' Complete a rotation — keep named axes verbatim, fill remainder from SVD
#'
#' Mirrors the tail of \code{ena.rotate.by.generalized}: the named axes
#' appear in the output exactly as provided, and the trailing columns come
#' from an SVD of the data deflated by all named axes.
#'
#' @param data         Numeric matrix (n_units x n_dims)
#' @param named_axes   Numeric matrix (n_dims x k); columns must be unit-norm
#' @param named_labels Character vector of length k
#' @return List with \code{rotation}, \code{eigenvalues}, \code{column_names}
#' @export
lq_complete_rotation <- function(data, named_axes, named_labels) {
    .Call(`_libqe_lq_complete_rotation`, data, named_axes, named_labels)
}

#' Means rotation
#'
#' For each group pair, computes a normalized mean-difference axis on the
#' progressively-deflated data and finishes with \code{lq_orthogonal_svd}.
#' The input is column-centered first, matching rENA's
#' \code{scale(data, scale=F, center=T)} at the top of \code{ena.rotate.by.mean}.
#'
#' Each element of \code{group_pairs} is a length-2 list \code{list(a, b)}
#' of 0-based row indices into \code{points}.
#'
#' @param points      Numeric matrix (n_units x n_dims)
#' @param group_pairs List of length k; each element is \code{list(a, b)}
#'   where \code{a} and \code{b} are 0-based integer index vectors
#' @return List with \code{rotation}, \code{eigenvalues}, \code{column_names}
#' @export
lq_means_rotation <- function(points, group_pairs) {
    .Call(`_libqe_lq_means_rotation`, points, group_pairs)
}

