# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Number of upper-triangle pairs for n codes
#' @param n Number of codes
#' @return Integer: n*(n-1)/2
#' @export
choose_two <- function(n) {
    .Call(`_libqe_choose_two`, n)
}

#' Upper-triangle index pairs
#' @param len Number of codes (side length of square matrix)
#' @param row -1 = both rows, 0 = row indices only, 1 = col indices only
#' @export
connection_indices <- function(len, row = -1L) {
    .Call(`_libqe_connection_indices`, len, row)
}

#' Pairwise products → upper-triangle vector
#' @param v Numeric vector of code values
#' @export
code_connections <- function(v) {
    .Call(`_libqe_code_connections`, v)
}

#' Fold a directed (n*n) vector into an undirected upper-triangle vector
#' @param v Numeric vector of length n*n
#' @export
fold_directed_network <- function(v) {
    .Call(`_libqe_fold_directed_network`, v)
}

#' Flatten an adjacency matrix to a connection vector
#' @param x Numeric matrix
#' @param full TRUE = full n*n (directed); FALSE = upper triangle (undirected)
#' @export
network_to_vector <- function(x, full = TRUE) {
    .Call(`_libqe_network_to_vector`, x, full)
}

#' Code-name pairs for upper-triangle positions ("A & B")
#' @param v Character vector of code names
#' @export
connection_names <- function(v) {
    .Call(`_libqe_connection_names`, v)
}

#' Row-wise L2 (sphere) normalization
#' @param m Numeric matrix
#' @export
normalize_networks <- function(m) {
    .Call(`_libqe_normalize_networks`, m)
}

#' Max-norm scaling (divide all rows by the largest row L2 norm)
#' @param m Numeric matrix
#' @export
scale_networks <- function(m) {
    .Call(`_libqe_scale_networks`, m)
}

#' Center points (subtract column means)
#' @param values Numeric matrix
#' @export
center_points <- function(values) {
    .Call(`_libqe_center_points`, values)
}

#' Confidence interval for the mean of a group of ENA unit points
#'
#' For each dimension computes a t-based CI:
#' \code{mean ± t(α/2, n-1) × (SD / sqrt(n))} where \code{α = 1 - conf_level}.
#'
#' @param points     Numeric matrix (units x dims) — one row per unit in the group
#' @param conf_level Confidence level (default 0.95)
#' @return Numeric matrix (n_dims x 3): columns are [mean, ci_lower, ci_upper].
#'   When \code{nrow(points) == 1} the CI bounds are \code{±Inf}.
#' @export
mean_ci <- function(points, conf_level = 0.95) {
    .Call(`_libqe_mean_ci`, points, conf_level)
}

#' Outlier interval based on IQR (Tukey fence) for a group of ENA unit points
#'
#' For each dimension: \code{lower = -iqr_factor * IQR}, \code{upper = +iqr_factor * IQR}.
#' Equivalent to rENA's:
#' \preformatted{
#'   oi <- c(IQR(pts[,1]), ...) * iqr_factor
#'   matrix(rep(oi, 2), ncol = n_dims, byrow = TRUE) * c(-1, 1)
#' }
#' IQR uses R's default \code{type = 7} quantile.
#'
#' @param points     Numeric matrix (units x dims) — one row per unit in the group
#' @param iqr_factor Multiplier applied to the IQR (default 1.5, the Tukey fence)
#' @return Numeric matrix (n_dims x 2): columns are [lower, upper].
#' @export
outlier_ci <- function(points, iqr_factor = 1.5) {
    .Call(`_libqe_outlier_ci`, points, iqr_factor)
}

#' Two-group comparison statistics
#'
#' Computes per-dimension parametric and non-parametric statistics for two
#' groups of ENA unit points.  Equivalent to \code{group.stats()} in rENA-api,
#' moved to the C++ layer so all language bindings share a single implementation.
#'
#' \strong{Parametric (Welch two-sample t-test):}
#' \itemize{
#'   \item \code{t}        — Welch t-statistics
#'   \item \code{parameter}— Welch–Satterthwaite degrees of freedom
#'   \item \code{pvalue}   — two-tailed p-values
#'   \item \code{effect}   — Cohen's d (pooled-SD: \code{(μ1−μ2)/pooled_sd})
#'   \item \code{mean}     — 2×n_dims matrix, row 1 = group1, row 2 = group2
#'   \item \code{std.dev}  — 2×n_dims matrix of sample standard deviations
#' }
#'
#' \strong{Non-parametric (Wilcoxon rank-sum):}
#' \itemize{
#'   \item \code{U}        — rank-sum U for group 1 (= R's \code{wilcox.test} W)
#'   \item \code{pvalue}   — two-tailed p-values (normal approx, tie + continuity correction)
#'   \item \code{effect}   — rank-biserial: \code{1 − 2·U / (n1·n2)}
#'   \item \code{median}   — 2×n_dims matrix of medians
#' }
#'
#' Entries are \code{NA} when a statistic is undefined (e.g. n < 2 for
#' parametric tests).
#'
#' @param g1 Numeric matrix (n1 × n_dims) — unit points for group 1
#' @param g2 Numeric matrix (n2 × n_dims) — unit points for group 2
#' @return Named list with \code{N}, \code{parametric}, and \code{nonparametric}
#'   sub-lists, matching the structure of rENA-api's \code{group.stats()}.
#' @export
group_stats <- function(g1, g2) {
    .Call(`_libqe_group_stats`, g1, g2)
}

#' Pearson correlation with CI between ENA points and centroids
#' @param points  Numeric matrix (units x dims)
#' @param centroids Numeric matrix (units x dims)
#' @param conf_level Confidence level (default 0.95)
#' @export
ena_correlation <- function(points, centroids, conf_level = 0.95) {
    .Call(`_libqe_ena_correlation`, points, centroids, conf_level)
}

#' Least-squares node positions for undirected ENA
#' @param adj_mats Numeric matrix of line weights (units x connections)
#' @param t        Numeric matrix of rotated points (units x dims)
#' @param num_dims Number of dimensions
#' @return List with nodes, centroids, weights, points
#' @export
node_positions <- function(adj_mats, t, num_dims) {
    .Call(`_libqe_node_positions`, adj_mats, t, num_dims)
}

#' Least-squares node positions for directed ENA
#' @param line_weights Numeric matrix (units x connections)
#' @param points       Numeric matrix of rotated points (units x dims)
#' @param num_dims     Number of dimensions
#' @return List with nodes, centroids, weights, points
#' @export
directed_node_positions <- function(line_weights, points, num_dims) {
    .Call(`_libqe_directed_node_positions`, line_weights, points, num_dims)
}

#' Directed node positions with paired ground+response rows combined
#' @param line_weights Numeric matrix (units x connections)
#' @param points       Numeric matrix of rotated points (units x dims)
#' @param num_dims     Number of dimensions
#' @return List with nodes, centroids, weights, points
#' @export
directed_node_positions_combine_pairs <- function(line_weights, points, num_dims) {
    .Call(`_libqe_directed_node_positions_combine_pairs`, line_weights, points, num_dims)
}

#' Core connection matrix for one ground+response pair
#' @param ground          Numeric row vector of ground (context) code values
#' @param response        Numeric row vector of response code values
#' @param response_weight Scalar weight applied to the response self-connection
#' @param ordered         TRUE = directed; FALSE = undirected
#' @export
connection_matrix <- function(ground, response, response_weight = 1.0, ordered = TRUE) {
    .Call(`_libqe_connection_matrix`, ground, response, response_weight, ordered)
}

#' Traditional stanza-window accumulation (rENA model)
#'
#' For each row k in a single conversation's code matrix, accumulates
#' connections over a back/forward window.
#'
#' \strong{Undirected} (\code{ordered = FALSE}, default): upper-triangle
#' co-occurrences with back/forward-reference corrections.
#' Returns \code{n_rows × choose_two(n_codes)}.
#'
#' \strong{Directed} (\code{ordered = TRUE}): focal row k as response,
#' sum of prior window rows as ground, using the directed connection formula.
#' \code{window_forward} is ignored. Returns \code{n_rows × n_codes²}.
#'
#' @param codes          Numeric matrix (rows = lines, cols = codes) for ONE conversation
#' @param window_back    Number of prior lines in window (default 1); use .Machine$integer.max for Inf
#' @param window_forward Number of subsequent lines (default 0; ignored when ordered = TRUE)
#' @param binary         If TRUE, binarise non-zero connection counts
#' @param ordered        If TRUE, return directed n² output; FALSE (default) returns upper-tri
#' @return Undirected: (n_rows × choose_two(n_codes)); directed: (n_rows × n_codes²)
#' @export
accumulate_stanza <- function(codes, window_back = 1L, window_forward = 0L, binary = TRUE, ordered = FALSE) {
    .Call(`_libqe_accumulate_stanza`, codes, window_back, window_forward, binary, ordered)
}

#' Compute a column-major linear index into a multi-dimensional array
#'
#' Equivalent to tma's flat_index(). Throws if lengths of `indices`
#' and `dims` differ.
#'
#' @param indices 0-based integer vector of per-dimension indices
#' @param dims    Integer vector of array dimensions
#' @return Scalar integer linear index
#' @export
flat_index <- function(indices, dims) {
    .Call(`_libqe_flat_index`, indices, dims)
}

#' Per-row upper-triangle co-occurrence matrix
#'
#' For each row in \code{codes}, computes the pairwise code products
#' (upper-triangle) and optionally binarizes. Output has
#' \code{choose(n_codes, 2)} columns.
#'
#' @param codes  Numeric matrix (rows = observations, cols = codes)
#' @param binary If TRUE, binarise non-zero co-occurrences (default TRUE)
#' @return Numeric matrix (n_rows x choose_two(n_codes))
#' @export
row_connections <- function(codes, binary = TRUE) {
    .Call(`_libqe_row_connections`, codes, binary)
}

#' Rolling backward window sum of a code matrix
#'
#' For each row k, sums the raw code values over rows
#' \code{[max(0, k - window_size + 1), k]}. Returns a matrix of the same
#' shape as \code{codes}. \code{window_size <= 0} is treated as 1
#' (current row only).
#'
#' @param codes       Numeric matrix (rows = observations, cols = codes)
#' @param window_size Number of rows to look back (default 1)
#' @return Numeric matrix (same dimensions as \code{codes})
#' @export
rolling_window_sum <- function(codes, window_size = 1L) {
    .Call(`_libqe_rolling_window_sum`, codes, window_size)
}

#' Ground/response accumulation for one unit (tma model)
#'
#' @param codes      Numeric matrix for the full context (n_rows x n_codes)
#' @param unit_rows  0-based integer vector of rows belonging to this unit
#' @param decay_fn   R function mapping a numeric distance vector to weights
#' @param ordered    TRUE = directed; FALSE = undirected (upper-tri)
#' @return Numeric vector of connection counts
#' @export
accumulate_unit <- function(codes, unit_rows, decay_fn, ordered = FALSE) {
    .Call(`_libqe_accumulate_unit`, codes, unit_rows, decay_fn, ordered)
}

#' Ground/response accumulation for one unit — returns unit vector and per-row matrix
#'
#' Equivalent to tma's accumulate_network() but without R-env-var setup.
#' The decay function receives a distance vector (response=0, older rows
#' have larger values) and returns a weight vector of the same length.
#'
#' @param codes      Numeric matrix (n_rows x n_codes)
#' @param unit_rows  0-based integer vector of rows belonging to this unit
#' @param decay_fn   R function(distances) -> weights
#' @param ordered    TRUE = directed (full p^2); FALSE = undirected (upper-tri)
#' @return List with `networks` (vector) and `row_networks` (matrix)
#' @export
accumulate_unit_with_rows <- function(codes, unit_rows, decay_fn, ordered = FALSE) {
    .Call(`_libqe_accumulate_unit_with_rows`, codes, unit_rows, decay_fn, ordered)
}

#' Tensor-based multi-modal accumulation for one unit (tma model)
#'
#' Pure-C++ port of tma's apply_tensor().  Accepts 0-based index vectors
#' for sender/receiver/mode dimensions and a pre-converted integer context
#' lookup matrix.
#'
#' @param tensor         Numeric vector (column-major flat tensor)
#' @param dims           Integer vector of tensor dimensions
#' @param dims_sender    0-based sender axis indices
#' @param dims_receiver  0-based receiver axis indices
#' @param dims_mode      0-based mode axis indices
#' @param context_lookup Integer matrix (n_context_rows x n_factors), 0-based
#' @param unit_rows      0-based response-row indices for this unit
#' @param codes          Numeric matrix (n_context_rows x n_codes)
#' @param times          Numeric vector of timestamps per context row
#' @param ordered        TRUE = directed; FALSE = undirected
#' @return List with `connection_counts` (vector) and `row_connection_counts` (matrix)
#' @export
apply_tensor <- function(tensor, dims, dims_sender, dims_receiver, dims_mode, context_lookup, unit_rows, codes, times, ordered = TRUE) {
    .Call(`_libqe_apply_tensor`, tensor, dims, dims_sender, dims_receiver, dims_mode, context_lookup, unit_rows, codes, times, ordered)
}

#' Apply the TMA window/weight tensor, additionally returning per-response-row
#' window membership.
#'
#' Identical to \code{apply_tensor()} but also returns, for each response
#' (reference) row, the in-window ground rows and their resolved window sizes.
#' Powers the webtool Data View per-modality window-span hover. Kept as a
#' separate export so \code{apply_tensor()}'s ABI (and tma's direct .Call to it)
#' is unchanged.
#'
#' @param tensor         Numeric vector (column-major flat tensor)
#' @param dims           Integer vector of tensor dimensions
#' @param dims_sender    0-based sender axis indices
#' @param dims_receiver  0-based receiver axis indices
#' @param dims_mode      0-based mode axis indices
#' @param context_lookup Integer matrix (n_context_rows x n_factors), 0-based
#' @param unit_rows      0-based response-row indices for this unit
#' @param codes          Numeric matrix (n_context_rows x n_codes)
#' @param times          Numeric vector of timestamps per context row
#' @param ordered        TRUE = directed; FALSE = undirected
#' @return List with \code{connection_counts}, \code{row_connection_counts},
#'   \code{row_window_members} (list of 1-based ground-row index vectors, in
#'   \code{unit_rows} order) and \code{row_window_wins} (parallel resolved
#'   window sizes).
#' @export
apply_tensor_members <- function(tensor, dims, dims_sender, dims_receiver, dims_mode, context_lookup, unit_rows, codes, times, ordered = TRUE) {
    .Call(`_libqe_apply_tensor_members`, tensor, dims, dims_sender, dims_receiver, dims_mode, context_lookup, unit_rows, codes, times, ordered)
}

#' SVD rotation (matches prcomp(retx=F, scale=F, center=F, tol=0))
#'
#' Caller is responsible for centering upstream. Eigenvalues are stored as
#' \code{sdev^2} (variance) to match rENA's \code{ena.svd}.
#'
#' @param points Numeric matrix (n_units x n_dims)
#' @return List with \code{rotation} (n_dims x n_dims), \code{eigenvalues}
#'   (length n_dims, = sdev^2), and \code{column_names} ("SVD1", "SVD2", ...)
#' @export
ena_svd <- function(points) {
    .Call(`_libqe_ena_svd`, points)
}

#' Project a matrix onto the hyperplane orthogonal to a unit-norm axis
#'
#' Computes \code{data - (data \%*\% axis) \%*\% t(axis)}. The caller is
#' responsible for ensuring \code{axis} is unit-norm.
#'
#' @param data Numeric matrix (n_units x n_dims)
#' @param axis Numeric vector of length n_dims, unit-norm
#' @return Numeric matrix of the same shape as \code{data}
#' @export
deflate <- function(data, axis) {
    .Call(`_libqe_deflate`, data, axis)
}

#' Orthogonal SVD — orthonormalize named axes via QR, fill the rest from SVD
#'
#' Mirrors rENA's \code{orthogonal_svd()} in \code{ena.rotate.by.mean.R}:
#' the named axes in the output are the orthonormalized Q columns, not the
#' original \code{weights} columns. Use \code{complete_rotation} to keep
#' the named axes verbatim.
#'
#' @param data         Numeric matrix (n_units x n_dims)
#' @param weights      Numeric matrix (n_dims x k); columns are the named axes
#' @param named_labels Character vector of length k
#' @return List with \code{rotation}, \code{eigenvalues}, \code{column_names}
#' @export
orthogonal_svd <- function(data, weights, named_labels) {
    .Call(`_libqe_orthogonal_svd`, data, weights, named_labels)
}

#' Complete a rotation — keep named axes verbatim, fill remainder from SVD
#'
#' Mirrors the tail of \code{ena.rotate.by.generalized}: the named axes
#' appear in the output exactly as provided, and the trailing columns come
#' from an SVD of the data deflated by all named axes.
#'
#' @param data         Numeric matrix (n_units x n_dims)
#' @param named_axes   Numeric matrix (n_dims x k); columns must be unit-norm
#' @param named_labels Character vector of length k
#' @return List with \code{rotation}, \code{eigenvalues}, \code{column_names}
#' @export
complete_rotation <- function(data, named_axes, named_labels) {
    .Call(`_libqe_complete_rotation`, data, named_axes, named_labels)
}

#' Means rotation
#'
#' For each group pair, computes a normalized mean-difference axis on the
#' progressively-deflated data and finishes with \code{orthogonal_svd}.
#' The input is column-centered first, matching rENA's
#' \code{scale(data, scale=F, center=T)} at the top of \code{ena.rotate.by.mean}.
#'
#' Each element of \code{group_pairs} is a length-2 list \code{list(a, b)}
#' of 0-based row indices into \code{points}.
#'
#' @param points      Numeric matrix (n_units x n_dims)
#' @param group_pairs List of length k; each element is \code{list(a, b)}
#'   where \code{a} and \code{b} are 0-based integer index vectors
#' @return List with \code{rotation}, \code{eigenvalues}, \code{column_names}
#' @export
means_rotation <- function(points, group_pairs) {
    .Call(`_libqe_means_rotation`, points, group_pairs)
}

#' Generalized Means Rotation
#'
#' Computes a rotation axis that best represents a target variable's
#' contribution to the ENA point space, after controlling for covariates via
#' Lasso (coordinate-descent, k-fold CV).  Mirrors
#' \code{rENA::ena.rotate.by.generalized()}.
#'
#' The caller is responsible for building \code{x_model_matrix} (e.g. via
#' \code{model.matrix()}) and identifying \code{x1_cols} (0-based indices of
#' the target variable's columns, which receive \code{penalty_factor = 0}).
#' Categorical targets should be encoded as 0-based integers.
#'
#' @param V              Numeric matrix (n_units x n_connections) — ENA points.
#' @param x_model_matrix Numeric matrix (n_units x p) — model matrix for x axis.
#' @param x_target       Numeric vector length n — target variable (raw float
#'   for numeric; 0-based integer codes for categorical).
#' @param x1_cols        Integer vector of 0-based column indices in
#'   \code{x_model_matrix} that belong to the target variable (unpenalized).
#' @param x_categorical  Logical — TRUE if target is categorical.
#' @param x_n_groups     Integer — number of distinct groups (categorical only).
#' @param x_subset       Integer vector of 0-based row indices to subset for
#'   the x-axis GMR step (pass \code{integer(0)} to use all rows).
#' @param has_y          Logical — TRUE to compute a second GMR axis.
#' @param y_model_matrix Numeric matrix (n_units x p) — model matrix for y axis
#'   (ignored when \code{has_y = FALSE}).
#' @param y_target       Numeric vector — y-axis target (ignored when
#'   \code{has_y = FALSE}).
#' @param y1_cols        0-based column indices for y target (ignored when
#'   \code{has_y = FALSE}).
#' @param y_categorical  Logical (ignored when \code{has_y = FALSE}).
#' @param y_n_groups     Integer (ignored when \code{has_y = FALSE}).
#' @param n_lambda       Length of the Lasso lambda path (default 50).
#' @param k_folds        Cross-validation folds for lambda selection (default 5).
#' @param lasso_eps      \code{lambda_min = lasso_eps * lambda_max} (default 0.01).
#' @return List with \code{rotation}, \code{eigenvalues}, \code{column_names}.
#' @export
generalized_means_rotation <- function(V, x_model_matrix, x_target, x1_cols, x_categorical, x_n_groups, x_subset, has_y, y_model_matrix, y_target, y1_cols, y_categorical, y_n_groups, n_lambda = 50L, k_folds = 5L, lasso_eps = 0.01) {
    .Call(`_libqe_generalized_means_rotation`, V, x_model_matrix, x_target, x1_cols, x_categorical, x_n_groups, x_subset, has_y, y_model_matrix, y_target, y1_cols, y_categorical, y_n_groups, n_lambda, k_folds, lasso_eps)
}

#' Door lookback window pooling for a single block
#' @param block Numeric matrix of connection counts
#' @param lookback_size Window lookback size
#' @param aggregate_mean Logical: TRUE = mean, FALSE = sum
#' @param weighting_linear Logical: TRUE = linear weights, FALSE = equal
#' @param segment_ids Integer vector of segment IDs (0-indexed or 1-indexed)
#' @export
door_lookback_block <- function(block, lookback_size = 20L, aggregate_mean = FALSE, weighting_linear = FALSE, segment_ids = integer()) {
    .Call(`_libqe_door_lookback_block`, block, lookback_size, aggregate_mean, weighting_linear, segment_ids)
}

#' Door EMA smoothing for a single block
#' @param block Numeric matrix of connection counts
#' @param alpha Smoothing factor in (0, 1]
#' @param segment_ids Integer vector of segment IDs
#' @export
door_ema_block <- function(block, alpha = 0.1, segment_ids = integer()) {
    .Call(`_libqe_door_ema_block`, block, alpha, segment_ids)
}

#' Door lookback window pooling across units
#' @param conn_counts Numeric matrix of connection counts
#' @param unit_row_indices List of integer vectors of row indices (0-indexed or 1-indexed R converted)
#' @param lookback_sizes Integer vector of lookback sizes per unit
#' @param aggregate_mean Logical: TRUE = mean, FALSE = sum
#' @param weighting_linear Logical: TRUE = linear weights, FALSE = equal
#' @param segment_ids Optional integer vector of segment IDs
#' @export
door_lookback <- function(conn_counts, unit_row_indices, lookback_sizes, aggregate_mean = FALSE, weighting_linear = FALSE, segment_ids = integer()) {
    .Call(`_libqe_door_lookback`, conn_counts, unit_row_indices, lookback_sizes, aggregate_mean, weighting_linear, segment_ids)
}

#' Door EMA smoothing across units
#' @param conn_counts Numeric matrix of connection counts
#' @param unit_row_indices List of integer vectors of row indices
#' @param alpha Smoothing factor
#' @param segment_ids Optional integer vector of segment IDs
#' @export
door_ema <- function(conn_counts, unit_row_indices, alpha = 0.1, segment_ids = integer()) {
    .Call(`_libqe_door_ema`, conn_counts, unit_row_indices, alpha, segment_ids)
}

#' Fit 2D parametric polynomial curve with LOOCV-2D or AIC degree selection
#' @param points Numeric matrix (n x 2) of trajectory coordinates
#' @param t Numeric vector of time values (length n)
#' @param max_degree Maximum polynomial degree (default 3)
#' @param fixed_degree Exact degree to use when >= 1
#' @param criterion Criterion for degree selection: "loocv" or "aic"
#' @param basis Polynomial basis used for fitting: "orthogonal" or "raw"
#' @export
fit_trajectory_poly <- function(points, t = numeric(), max_degree = 3L, fixed_degree = 0L, criterion = "loocv", basis = "orthogonal") {
    .Call(`_libqe_fit_trajectory_poly`, points, t, max_degree, fixed_degree, criterion, basis)
}

#' Evaluate 2D parametric polynomial curve at specified time points
#' @param coeffs_x Polynomial coefficients for X
#' @param coeffs_y Polynomial coefficients for Y
#' @param t_eval Numeric vector of time evaluation points
#' @export
eval_trajectory_curve <- function(coeffs_x, coeffs_y, t_eval) {
    .Call(`_libqe_eval_trajectory_curve`, coeffs_x, coeffs_y, t_eval)
}

#' Evaluate trajectory differential geometry (velocities, speed, curvature, turns)
#' @param coeffs_x Polynomial coefficients for X
#' @param coeffs_y Polynomial coefficients for Y
#' @param t_eval Numeric vector of time evaluation points
#' @export
eval_trajectory_derivatives <- function(coeffs_x, coeffs_y, t_eval) {
    .Call(`_libqe_eval_trajectory_derivatives`, coeffs_x, coeffs_y, t_eval)
}

#' Integrated Euclidean distance between two trajectory polynomial curves
#' @param coeffs_ax Polynomial coeffs for Curve A X
#' @param coeffs_ay Polynomial coeffs for Curve A Y
#' @param coeffs_bx Polynomial coeffs for Curve B X
#' @param coeffs_by Polynomial coeffs for Curve B Y
#' @param t_start Integration start (default 0.0)
#' @param t_end Integration end (default 1.0)
#' @export
integrated_trajectory_distance <- function(coeffs_ax, coeffs_ay, coeffs_bx, coeffs_by, t_start = 0.0, t_end = 1.0) {
    .Call(`_libqe_integrated_trajectory_distance`, coeffs_ax, coeffs_ay, coeffs_bx, coeffs_by, t_start, t_end)
}

#' Lagged curve distance between follower and leader
#' @param coeffs_fol_x Polynomial coeffs for Follower X
#' @param coeffs_fol_y Polynomial coeffs for Follower Y
#' @param coeffs_ldr_x Polynomial coeffs for Leader X
#' @param coeffs_ldr_y Polynomial coeffs for Leader Y
#' @param lag Time lag in [0, 1)
#' @export
lagged_trajectory_distance <- function(coeffs_fol_x, coeffs_fol_y, coeffs_ldr_x, coeffs_ldr_y, lag = 0.0) {
    .Call(`_libqe_lagged_trajectory_distance`, coeffs_fol_x, coeffs_fol_y, coeffs_ldr_x, coeffs_ldr_y, lag)
}

#' Pairwise integrated trajectory distance matrix
#' @param all_coeffs_x List of X coefficient vectors
#' @param all_coeffs_y List of Y coefficient vectors
#' @export
pairwise_trajectory_distance <- function(all_coeffs_x, all_coeffs_y) {
    .Call(`_libqe_pairwise_trajectory_distance`, all_coeffs_x, all_coeffs_y)
}

#' Signed turn-lag distance between two agents at specific lag delta
#' @param pts_a Points matrix for agent A (n_a x 2)
#' @param pts_b Points matrix for agent B (n_b x 2)
#' @param times_a Turn times for agent A
#' @param times_b Turn times for agent B
#' @param delta Signed lag in turns
#' @export
signed_turn_lag <- function(pts_a, pts_b, times_a, times_b, delta) {
    .Call(`_libqe_signed_turn_lag`, pts_a, pts_b, times_a, times_b, delta)
}

#' Sweep signed turn lags to find optimal leader-follower lag
#' @param pts_a Points matrix for agent A (n_a x 2)
#' @param pts_b Points matrix for agent B (n_b x 2)
#' @param times_a Turn times for agent A
#' @param times_b Turn times for agent B
#' @param max_lag Maximum turn lag to evaluate (default 15)
#' @export
sweep_signed_turn_lags <- function(pts_a, pts_b, times_a, times_b, max_lag = 15L) {
    .Call(`_libqe_sweep_signed_turn_lags`, pts_a, pts_b, times_a, times_b, max_lag)
}

#' Distance-distance matrix correlation for stability analysis
#' @param X Numeric matrix
#' @param Y Numeric matrix
#' @export
dist_dist_correlation <- function(X, Y) {
    .Call(`_libqe_dist_dist_correlation`, X, Y)
}

