// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// choose_two
int choose_two(int n);
RcppExport SEXP _libqe_choose_two(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(choose_two(n));
    return rcpp_result_gen;
END_RCPP
}
// connection_indices
arma::umat connection_indices(int len, int row);
RcppExport SEXP _libqe_connection_indices(SEXP lenSEXP, SEXP rowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type len(lenSEXP);
    Rcpp::traits::input_parameter< int >::type row(rowSEXP);
    rcpp_result_gen = Rcpp::wrap(connection_indices(len, row));
    return rcpp_result_gen;
END_RCPP
}
// code_connections
arma::rowvec code_connections(arma::mat v);
RcppExport SEXP _libqe_code_connections(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(code_connections(v));
    return rcpp_result_gen;
END_RCPP
}
// fold_directed_network
arma::rowvec fold_directed_network(arma::vec v);
RcppExport SEXP _libqe_fold_directed_network(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(fold_directed_network(v));
    return rcpp_result_gen;
END_RCPP
}
// network_to_vector
arma::rowvec network_to_vector(arma::mat x, bool full);
RcppExport SEXP _libqe_network_to_vector(SEXP xSEXP, SEXP fullSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type full(fullSEXP);
    rcpp_result_gen = Rcpp::wrap(network_to_vector(x, full));
    return rcpp_result_gen;
END_RCPP
}
// connection_names
std::vector<std::string> connection_names(std::vector<std::string> v);
RcppExport SEXP _libqe_connection_names(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(connection_names(v));
    return rcpp_result_gen;
END_RCPP
}
// normalize_networks
arma::mat normalize_networks(arma::mat m);
RcppExport SEXP _libqe_normalize_networks(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize_networks(m));
    return rcpp_result_gen;
END_RCPP
}
// scale_networks
arma::mat scale_networks(arma::mat m);
RcppExport SEXP _libqe_scale_networks(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(scale_networks(m));
    return rcpp_result_gen;
END_RCPP
}
// center_points
arma::mat center_points(arma::mat values);
RcppExport SEXP _libqe_center_points(SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type values(valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(center_points(values));
    return rcpp_result_gen;
END_RCPP
}
// mean_ci
arma::mat mean_ci(arma::mat points, double conf_level);
RcppExport SEXP _libqe_mean_ci(SEXP pointsSEXP, SEXP conf_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_ci(points, conf_level));
    return rcpp_result_gen;
END_RCPP
}
// outlier_ci
arma::mat outlier_ci(arma::mat points, double iqr_factor);
RcppExport SEXP _libqe_outlier_ci(SEXP pointsSEXP, SEXP iqr_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< double >::type iqr_factor(iqr_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(outlier_ci(points, iqr_factor));
    return rcpp_result_gen;
END_RCPP
}
// group_stats
List group_stats(arma::mat g1, arma::mat g2);
RcppExport SEXP _libqe_group_stats(SEXP g1SEXP, SEXP g2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type g1(g1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type g2(g2SEXP);
    rcpp_result_gen = Rcpp::wrap(group_stats(g1, g2));
    return rcpp_result_gen;
END_RCPP
}
// ena_correlation
arma::mat ena_correlation(arma::mat points, arma::mat centroids, double conf_level);
RcppExport SEXP _libqe_ena_correlation(SEXP pointsSEXP, SEXP centroidsSEXP, SEXP conf_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type centroids(centroidsSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(ena_correlation(points, centroids, conf_level));
    return rcpp_result_gen;
END_RCPP
}
// node_positions
List node_positions(arma::mat adj_mats, arma::mat t, int num_dims);
RcppExport SEXP _libqe_node_positions(SEXP adj_matsSEXP, SEXP tSEXP, SEXP num_dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type adj_mats(adj_matsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type num_dims(num_dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(node_positions(adj_mats, t, num_dims));
    return rcpp_result_gen;
END_RCPP
}
// directed_node_positions
List directed_node_positions(arma::mat line_weights, arma::mat points, int num_dims);
RcppExport SEXP _libqe_directed_node_positions(SEXP line_weightsSEXP, SEXP pointsSEXP, SEXP num_dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type line_weights(line_weightsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type num_dims(num_dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(directed_node_positions(line_weights, points, num_dims));
    return rcpp_result_gen;
END_RCPP
}
// directed_node_positions_combine_pairs
List directed_node_positions_combine_pairs(arma::mat line_weights, arma::mat points, int num_dims);
RcppExport SEXP _libqe_directed_node_positions_combine_pairs(SEXP line_weightsSEXP, SEXP pointsSEXP, SEXP num_dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type line_weights(line_weightsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type num_dims(num_dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(directed_node_positions_combine_pairs(line_weights, points, num_dims));
    return rcpp_result_gen;
END_RCPP
}
// connection_matrix
arma::mat connection_matrix(arma::rowvec ground, arma::rowvec response, double response_weight, bool ordered);
RcppExport SEXP _libqe_connection_matrix(SEXP groundSEXP, SEXP responseSEXP, SEXP response_weightSEXP, SEXP orderedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type ground(groundSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type response(responseSEXP);
    Rcpp::traits::input_parameter< double >::type response_weight(response_weightSEXP);
    Rcpp::traits::input_parameter< bool >::type ordered(orderedSEXP);
    rcpp_result_gen = Rcpp::wrap(connection_matrix(ground, response, response_weight, ordered));
    return rcpp_result_gen;
END_RCPP
}
// accumulate_stanza
arma::mat accumulate_stanza(arma::mat codes, int window_back, int window_forward, bool binary, bool ordered);
RcppExport SEXP _libqe_accumulate_stanza(SEXP codesSEXP, SEXP window_backSEXP, SEXP window_forwardSEXP, SEXP binarySEXP, SEXP orderedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type codes(codesSEXP);
    Rcpp::traits::input_parameter< int >::type window_back(window_backSEXP);
    Rcpp::traits::input_parameter< int >::type window_forward(window_forwardSEXP);
    Rcpp::traits::input_parameter< bool >::type binary(binarySEXP);
    Rcpp::traits::input_parameter< bool >::type ordered(orderedSEXP);
    rcpp_result_gen = Rcpp::wrap(accumulate_stanza(codes, window_back, window_forward, binary, ordered));
    return rcpp_result_gen;
END_RCPP
}
// flat_index
int flat_index(std::vector<int> indices, std::vector<int> dims);
RcppExport SEXP _libqe_flat_index(SEXP indicesSEXP, SEXP dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type dims(dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(flat_index(indices, dims));
    return rcpp_result_gen;
END_RCPP
}
// row_connections
arma::mat row_connections(arma::mat codes, bool binary);
RcppExport SEXP _libqe_row_connections(SEXP codesSEXP, SEXP binarySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type codes(codesSEXP);
    Rcpp::traits::input_parameter< bool >::type binary(binarySEXP);
    rcpp_result_gen = Rcpp::wrap(row_connections(codes, binary));
    return rcpp_result_gen;
END_RCPP
}
// rolling_window_sum
arma::mat rolling_window_sum(arma::mat codes, int window_size);
RcppExport SEXP _libqe_rolling_window_sum(SEXP codesSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type codes(codesSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_window_sum(codes, window_size));
    return rcpp_result_gen;
END_RCPP
}
// accumulate_unit
arma::rowvec accumulate_unit(arma::mat codes, std::vector<int> unit_rows, Function decay_fn, bool ordered);
RcppExport SEXP _libqe_accumulate_unit(SEXP codesSEXP, SEXP unit_rowsSEXP, SEXP decay_fnSEXP, SEXP orderedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type codes(codesSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type unit_rows(unit_rowsSEXP);
    Rcpp::traits::input_parameter< Function >::type decay_fn(decay_fnSEXP);
    Rcpp::traits::input_parameter< bool >::type ordered(orderedSEXP);
    rcpp_result_gen = Rcpp::wrap(accumulate_unit(codes, unit_rows, decay_fn, ordered));
    return rcpp_result_gen;
END_RCPP
}
// accumulate_unit_with_rows
List accumulate_unit_with_rows(arma::mat codes, std::vector<int> unit_rows, Function decay_fn, bool ordered);
RcppExport SEXP _libqe_accumulate_unit_with_rows(SEXP codesSEXP, SEXP unit_rowsSEXP, SEXP decay_fnSEXP, SEXP orderedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type codes(codesSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type unit_rows(unit_rowsSEXP);
    Rcpp::traits::input_parameter< Function >::type decay_fn(decay_fnSEXP);
    Rcpp::traits::input_parameter< bool >::type ordered(orderedSEXP);
    rcpp_result_gen = Rcpp::wrap(accumulate_unit_with_rows(codes, unit_rows, decay_fn, ordered));
    return rcpp_result_gen;
END_RCPP
}
// apply_tensor
List apply_tensor(arma::vec tensor, std::vector<int> dims, std::vector<int> dims_sender, std::vector<int> dims_receiver, std::vector<int> dims_mode, arma::imat context_lookup, std::vector<int> unit_rows, arma::mat codes, arma::vec times, bool ordered);
RcppExport SEXP _libqe_apply_tensor(SEXP tensorSEXP, SEXP dimsSEXP, SEXP dims_senderSEXP, SEXP dims_receiverSEXP, SEXP dims_modeSEXP, SEXP context_lookupSEXP, SEXP unit_rowsSEXP, SEXP codesSEXP, SEXP timesSEXP, SEXP orderedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type tensor(tensorSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type dims_sender(dims_senderSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type dims_receiver(dims_receiverSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type dims_mode(dims_modeSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type context_lookup(context_lookupSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type unit_rows(unit_rowsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type codes(codesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type times(timesSEXP);
    Rcpp::traits::input_parameter< bool >::type ordered(orderedSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_tensor(tensor, dims, dims_sender, dims_receiver, dims_mode, context_lookup, unit_rows, codes, times, ordered));
    return rcpp_result_gen;
END_RCPP
}
// apply_tensor_members
List apply_tensor_members(arma::vec tensor, std::vector<int> dims, std::vector<int> dims_sender, std::vector<int> dims_receiver, std::vector<int> dims_mode, arma::imat context_lookup, std::vector<int> unit_rows, arma::mat codes, arma::vec times, bool ordered);
RcppExport SEXP _libqe_apply_tensor_members(SEXP tensorSEXP, SEXP dimsSEXP, SEXP dims_senderSEXP, SEXP dims_receiverSEXP, SEXP dims_modeSEXP, SEXP context_lookupSEXP, SEXP unit_rowsSEXP, SEXP codesSEXP, SEXP timesSEXP, SEXP orderedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type tensor(tensorSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type dims_sender(dims_senderSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type dims_receiver(dims_receiverSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type dims_mode(dims_modeSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type context_lookup(context_lookupSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type unit_rows(unit_rowsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type codes(codesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type times(timesSEXP);
    Rcpp::traits::input_parameter< bool >::type ordered(orderedSEXP);
    rcpp_result_gen = Rcpp::wrap(apply_tensor_members(tensor, dims, dims_sender, dims_receiver, dims_mode, context_lookup, unit_rows, codes, times, ordered));
    return rcpp_result_gen;
END_RCPP
}
// ena_svd
List ena_svd(arma::mat points);
RcppExport SEXP _libqe_ena_svd(SEXP pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type points(pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(ena_svd(points));
    return rcpp_result_gen;
END_RCPP
}
// deflate
arma::mat deflate(arma::mat data, arma::vec axis);
RcppExport SEXP _libqe_deflate(SEXP dataSEXP, SEXP axisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type axis(axisSEXP);
    rcpp_result_gen = Rcpp::wrap(deflate(data, axis));
    return rcpp_result_gen;
END_RCPP
}
// orthogonal_svd
List orthogonal_svd(arma::mat data, arma::mat weights, std::vector<std::string> named_labels);
RcppExport SEXP _libqe_orthogonal_svd(SEXP dataSEXP, SEXP weightsSEXP, SEXP named_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type named_labels(named_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(orthogonal_svd(data, weights, named_labels));
    return rcpp_result_gen;
END_RCPP
}
// complete_rotation
List complete_rotation(arma::mat data, arma::mat named_axes, std::vector<std::string> named_labels);
RcppExport SEXP _libqe_complete_rotation(SEXP dataSEXP, SEXP named_axesSEXP, SEXP named_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type named_axes(named_axesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type named_labels(named_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(complete_rotation(data, named_axes, named_labels));
    return rcpp_result_gen;
END_RCPP
}
// means_rotation
List means_rotation(arma::mat points, List group_pairs);
RcppExport SEXP _libqe_means_rotation(SEXP pointsSEXP, SEXP group_pairsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< List >::type group_pairs(group_pairsSEXP);
    rcpp_result_gen = Rcpp::wrap(means_rotation(points, group_pairs));
    return rcpp_result_gen;
END_RCPP
}
// generalized_means_rotation
List generalized_means_rotation(arma::mat V, arma::mat x_model_matrix, arma::vec x_target, IntegerVector x1_cols, bool x_categorical, int x_n_groups, IntegerVector x_subset, bool has_y, arma::mat y_model_matrix, arma::vec y_target, IntegerVector y1_cols, bool y_categorical, int y_n_groups, int n_lambda, int k_folds, double lasso_eps);
RcppExport SEXP _libqe_generalized_means_rotation(SEXP VSEXP, SEXP x_model_matrixSEXP, SEXP x_targetSEXP, SEXP x1_colsSEXP, SEXP x_categoricalSEXP, SEXP x_n_groupsSEXP, SEXP x_subsetSEXP, SEXP has_ySEXP, SEXP y_model_matrixSEXP, SEXP y_targetSEXP, SEXP y1_colsSEXP, SEXP y_categoricalSEXP, SEXP y_n_groupsSEXP, SEXP n_lambdaSEXP, SEXP k_foldsSEXP, SEXP lasso_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_model_matrix(x_model_matrixSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_target(x_targetSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x1_cols(x1_colsSEXP);
    Rcpp::traits::input_parameter< bool >::type x_categorical(x_categoricalSEXP);
    Rcpp::traits::input_parameter< int >::type x_n_groups(x_n_groupsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x_subset(x_subsetSEXP);
    Rcpp::traits::input_parameter< bool >::type has_y(has_ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y_model_matrix(y_model_matrixSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y_target(y_targetSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y1_cols(y1_colsSEXP);
    Rcpp::traits::input_parameter< bool >::type y_categorical(y_categoricalSEXP);
    Rcpp::traits::input_parameter< int >::type y_n_groups(y_n_groupsSEXP);
    Rcpp::traits::input_parameter< int >::type n_lambda(n_lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type k_folds(k_foldsSEXP);
    Rcpp::traits::input_parameter< double >::type lasso_eps(lasso_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(generalized_means_rotation(V, x_model_matrix, x_target, x1_cols, x_categorical, x_n_groups, x_subset, has_y, y_model_matrix, y_target, y1_cols, y_categorical, y_n_groups, n_lambda, k_folds, lasso_eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_libqe_choose_two", (DL_FUNC) &_libqe_choose_two, 1},
    {"_libqe_connection_indices", (DL_FUNC) &_libqe_connection_indices, 2},
    {"_libqe_code_connections", (DL_FUNC) &_libqe_code_connections, 1},
    {"_libqe_fold_directed_network", (DL_FUNC) &_libqe_fold_directed_network, 1},
    {"_libqe_network_to_vector", (DL_FUNC) &_libqe_network_to_vector, 2},
    {"_libqe_connection_names", (DL_FUNC) &_libqe_connection_names, 1},
    {"_libqe_normalize_networks", (DL_FUNC) &_libqe_normalize_networks, 1},
    {"_libqe_scale_networks", (DL_FUNC) &_libqe_scale_networks, 1},
    {"_libqe_center_points", (DL_FUNC) &_libqe_center_points, 1},
    {"_libqe_mean_ci", (DL_FUNC) &_libqe_mean_ci, 2},
    {"_libqe_outlier_ci", (DL_FUNC) &_libqe_outlier_ci, 2},
    {"_libqe_group_stats", (DL_FUNC) &_libqe_group_stats, 2},
    {"_libqe_ena_correlation", (DL_FUNC) &_libqe_ena_correlation, 3},
    {"_libqe_node_positions", (DL_FUNC) &_libqe_node_positions, 3},
    {"_libqe_directed_node_positions", (DL_FUNC) &_libqe_directed_node_positions, 3},
    {"_libqe_directed_node_positions_combine_pairs", (DL_FUNC) &_libqe_directed_node_positions_combine_pairs, 3},
    {"_libqe_connection_matrix", (DL_FUNC) &_libqe_connection_matrix, 4},
    {"_libqe_accumulate_stanza", (DL_FUNC) &_libqe_accumulate_stanza, 5},
    {"_libqe_flat_index", (DL_FUNC) &_libqe_flat_index, 2},
    {"_libqe_row_connections", (DL_FUNC) &_libqe_row_connections, 2},
    {"_libqe_rolling_window_sum", (DL_FUNC) &_libqe_rolling_window_sum, 2},
    {"_libqe_accumulate_unit", (DL_FUNC) &_libqe_accumulate_unit, 4},
    {"_libqe_accumulate_unit_with_rows", (DL_FUNC) &_libqe_accumulate_unit_with_rows, 4},
    {"_libqe_apply_tensor", (DL_FUNC) &_libqe_apply_tensor, 10},
    {"_libqe_apply_tensor_members", (DL_FUNC) &_libqe_apply_tensor_members, 10},
    {"_libqe_ena_svd", (DL_FUNC) &_libqe_ena_svd, 1},
    {"_libqe_deflate", (DL_FUNC) &_libqe_deflate, 2},
    {"_libqe_orthogonal_svd", (DL_FUNC) &_libqe_orthogonal_svd, 3},
    {"_libqe_complete_rotation", (DL_FUNC) &_libqe_complete_rotation, 3},
    {"_libqe_means_rotation", (DL_FUNC) &_libqe_means_rotation, 2},
    {"_libqe_generalized_means_rotation", (DL_FUNC) &_libqe_generalized_means_rotation, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_libqe(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
